name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We love new ideas! Please describe your feature request.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: What would you like to see added/improved?
      placeholder: "It would be great if the SDK could automatically ..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case / motivation
      description: How would this feature help you or others?
      placeholder: "This would save me ... hours per week because ..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any other solutions or workarounds you tried?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, API docs links, examples, etc.