package com.packeta.sdk.util.pricing.enums;

public enum TransportType {
    TO_DETERMINE,
    // CZ
    Z_POINT_PP, Z_BOX, HOME_STANDARD, EVENING_HD,

    // HU
    HU_Z_POINT_PP, HU_HOME_DELIVERY_HD, HU_EXPRESS_ONE_HD, HU_FOXPOST_BOX, HU_HUNGARIAN_POST_BOX, HU_HUNGARIAN_POST_HD, HU_HUNGARIAN_POST_PP, HU_Z_BOX,

    // PL
    PL_Z_POINT_PP, PL_HOME_DELIVERY_HD, PL_INPOST_PACZKOMATY_BOX, PL_POLISH_POST_PP,

    // RO
    RO_Z_POINT_PP, RO_HOME_DELIVERY_HD, RO_CARGUS_HD, RO_FAN_COURIER_BOX, RO_FAN_COURIER_HD, RO_SAMEDAY_BOX,

    // SK
    SK_Z_POINT_PP,

    // AT
    AT_AUSTRIAN_POST_HD, AT_DPD_HD,

    // BE
    BE_BELGIAN_POST_HD, BE_BELGIAN_POST_PP, BE_DUTCH_POST_HD,

    // BG
    BG_HOME_DELIVERY_HD, BG_BOXNOW_BOX, BG_ECONT_BOX, BG_ECONT_HD, BG_ECONT_PP, BG_SAMEDAY_BOX, BG_SAMEDAY_HD, BG_SPEEDY_HD, BG_SPEEDY_PP,

    // HR
    HR_BOXNOW_BOX, HR_CROATIAN_POST_HD, HR_CROATIAN_POST_PP, HR_OVERSEAS_HD, HR_OVERSEAS_PP,

    // CY
    CY_BOXNOW_BOX,

    // DK
    DK_POST_NORD_HD, DK_POST_NORD_PP,

    // EE
    EE_LITHUANIAN_POST_HD, EE_OMNIVA_BOX, EE_OMNIVA_HD, EE_OMNIVA_PP, EE_VENIPAK_BOX, EE_VENIPAK_HD, EE_VENIPAK_PP,

    // FI
    FI_MATKAHUOLTO_BOX, FI_MATKAHUOLTO_HD, FI_MATKAHUOLTO_PP, FI_POST_NORD_HD, FI_POST_NORD_PP,

    // FR
    FR_COLIS_PRIVE_HD, FR_COLISSIMO_HD, FR_COLISSIMO_PP, FR_MONDIAL_RELAY_PP,

    // DE
    DE_HOME_DELIVERY_HD, DE_HERMES_HD, DE_HERMES_PP,

    // GR
    GR_ACS_HD, GR_ACS_PP, GR_BOXNOW_BOX, GR_ELTA_COURIER_HD, GR_ELTA_COURIER_PP, GR_SPEEDEX_HD, GR_TAXYDROMIKI_HD,

    // IE
    IE_FASTWAY_COURIERS_HD, IE_FEDEX_HD_CONNECT_PLUS, IE_FEDEX_HD_PRIORITY,

    // IT
    IT_BARTOLINI_BOX, IT_BARTOLINI_HD, IT_BARTOLINI_PP, IT_HR_PARCEL_HD, IT_ITALIAN_POST_HD, IT_ITALIAN_POST_PP, IT_ITALIAN_POST_PUNTO_POSTE_PP,

    // LV
    LV_OMNIVA_HD, LV_VENIPAK_BOX, LV_VENIPAK_HD, LV_VENIPAK_PP,

    // LT
    LT_LITHUANIAN_POST_BOX, LT_LITHUANIAN_POST_HD, LT_OMNIVA_BOX, LT_OMNIVA_HD, LT_VENIPAK_BOX, LT_VENIPAK_HD, LT_VENIPAK_PP,

    // LU
    LU_DPD_HD, LU_LUXEMBOURG_POST_HD,

    // NL
    NL_DHL_HD, NL_DHL_PP, NL_DUTCH_POST_HD,

    // PT
    PT_MRW_HD, PT_MRW_PP;


}
